### ISSUE TITLE
Set up the arche-ref-sources

### ISSUE THREAD

**Issue by zozlak** [acdh-oeaw/arche-docker-config#19]
### Links

* https://github.com/acdh-oeaw/arche-ref-sources
* [Seta's presentation](https://oeawacat.sharepoint.com/:p:/r/sites/ACDH-CH_i_dsie/_layouts/15/Doc.aspx?sourcedoc=%7B4255AD96-6382-43E6-BD60-F39942F1960F%7D&file=2025-05-08_ARCHE_NamedEntities.pptx&action=edit&mobileredirect=true)

### TODO

* [x] Scrap places withouth `acdh:hasTitle`, `acdh:hasLatitude`, `acdh:hasLongitude` or `acdh:hasWKT`
  * For the `acdh:hasTitle` scrap only a single prefered label and if it does not exist (for this entity or because of the authority file's data model) scrap only labels in `de` and `en`.
  * Taking into account which authority file provides with properties:
    ```
    --class acdh:Place --withoutProperty acdh:hasTitle     place-title.yaml
    --class acdh:Place --withoutProperty acdh:hasLatitude  place-latlon.yaml
    --class acdh:Place --withoutProperty acdh:hasLongitude place-latlon.yaml
    --class acdh:Place --withoutProperty acdh:hasWKT       place-wkt.yaml
    ```
  * support (order means priority)
    * [x] Geonames​
    * [x] Getty
    * [x] GND
    * [x] Gazzetteer​
    * [x] Pleiades ​
    * [x] Wikidata
* [x] Scrap persons without `acdh:hasTilte`, `acdh:hasFirstName` or `acdhHasLastName`
  ```
  --class acdh:Person --withoutProperty acdh:hasTitle     person.yaml
  --class acdh:Person --withoutProperty acdh:hasFirstName person.yaml
  --class acdh:Person --withoutProperty acdh:hasLastName  person.yaml
  ```
  * Scrap only a single prefered label and if it does not exist (for this entity or because of the authority file's data model) scrap only labels in `de` and `en`.
  * Support (order means priority)
    * [x] Wikidata
    * [x] ORCID
    * [x] GND
    * [x] VIAF
* [x] Scrap organisations without `acdh:hasTitle`
  ```
  --class acdh:Organisation --withoutProperty acdh:hasTitle    organisation.yaml
  ```
  * Scrap only a single prefered label and if it does not exist (for this entity or because of the authority file's data model) scrap only labels in `de` and `en`.
  * Support (order means priority)
    * [x] Wikidata
    * [x] GND
    * [x] VIAF
    * [x] ROR

**Comment by zozlak** [comment]
Looks more or less ready:

* [config files](https://github.com/acdh-oeaw/arche-docker-config/tree/arche/ref-sources)
* [script](https://github.com/acdh-oeaw/arche-docker-config/blob/arche/updateFromRefSources.sh)

Here and now triggered at the end of the [backup.sh](https://github.com/acdh-oeaw/arche-docker-config/blob/arche/backup.sh).

Let's see how it goes.

**Comment by zozlak** [comment]
Seems to work
